### PR TITLE
Identify PXE clients by the vendor class identifier (option 60) instead of checking for existence of parameter request list (option 55)

### PR DESCRIPTION
**Pull request by bias-keenly**
Fix for https://github.com/mpetazzoni/ptftpd/issues/16

### CODE REVIEW

**Comment by mpetazzoni** [comment]
Thanks for the PR! Great investigative work and thanks for following it up with a contribution!

Would you be ok making the old behavior still available (via a command-line flag) in case someone deals with a PXE client that doesn't set option 60's field to a value that begins with `PXEClient`?

Something like a `--answer-all-pxe-requests` for example. In terms of wiring this up you might want to extract a predicate lambda that returns the boolean value for `is_pxe_request`, and pass the appropriate predicate to the constructor of `DhcpPacket` based on the value of this `--answer-all-pxe-requests` option.

Thoughts?

**Comment by kyle-zadara** [comment]
No problem, will update the PR in the next couple days as time allows.  How about naming it `--answer-all-dhcp-requests`?  The problem with the current implementation is that it responds to _all_ DHCP requests, PXE or not.  It also does not offer DNS so the unsuspecting systems that get IPs from it will not be able to resolve any names.  A few of my colleagues found this out the hard way and got blackholed for a bit.

May I propose the addition of DHCP option 6 (DNS) as an optional flag `--nameservers` which would be a csv string of DNS servers to offer.

One additional proposal is to add a `--dhcp-range` option.  My use case involves running this on a subnet with static IPs, so offering the entire subnet of the listening interface may cause IP conflicts.  

Please let me know if you have any thoughts on these proposals.  I will be implementing them for my project and interested in contributing these features if desired.

**Comment by mpetazzoni** [comment]
All great proposals! Feel free to send PRs and I'll review them!

**Comment by bias-keenly** [comment]
Thanks! I will submit PRs for DNS and DHCP scope in the next few days.

I have committed the requested change for this PR; allowing for all DHCP requests to be responded to by adding `-a` or `--answer-all-dhcp-requests`.

I didn't quite understand the proposed implementation for this flag, but did my best to keep it simple and logical.  Let me know if it needs changing.

**Pull request merged**
